name: Generate Snake ğŸ

on:
  schedule:
    - cron: "0 0 * * *"  # todo dia Ã  meia-noite
  workflow_dispatch:

jobs:
  build:
    name: Generate Snake SVG
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: Gerar snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: iagocdev
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit do arquivo gerado
        uses: EndBug/add-and-commit@v9
        with:
          message: "ğŸ snake atualizado"
          add: "dist/github-contribution-grid-snake.svg"

      - name: Enviar para branch output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
